---
- name: Set up apache
  hosts: localhost
  gather_facts: yes
  tasks: 
    - name: Install Apache
      yum:
        name: httpd
        state: latest
    
    - name: start and enable apache
      service:
        name: httpd
        state: started
        enabled: yes